donenv/urls.py
from django.contrib import admin
from django.urls import path
from app import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from app.forms import MyPasswordResetForm, MySetPasswordForm

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.index, name="index"),
    path("gallery/", views.gallery, name="gallery"),
    path("login-admin/", views.login_admin.as_view(), name="login_admin"),
    path("login-donor/", views.login_donor.as_view(), name="login_donor"),
    path("login-volunteer/", views.login_volunteer.as_view(), name="login_volunteer"),
    path("signup-donor/", views.signup_donor.as_view(), name="signup_donor"),
    path("signup-volunteer/", views.signup_volunteer.as_view(), name="signup_volunteer"),
    path("index-admin/", views.index_admin, name="index_admin"),

    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='password_reset.html', form_class=MyPasswordResetForm),name='password_reset'),
    path('password-reset/done', auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'),name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html',form_class=MySetPasswordForm), name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'), name='password_reset_complete'),



    # admin dashboard
    path("pending-donation/", views.pending_donation, name="pending_donation"),
    path("accepted-donation/", views.accepted_donation, name="accepted_donation"),
    path("rejected-donation/", views.rejected_donation, name="rejected_donation"),
    path(
        "volunteerallocated-donation/",
        views.volunteerallocated_donation,
        name="volunteerallocated_donation",
    ),
    path("donationrec-admin/", views.donationrec_admin, name="donationrec_admin"),
    path(
        "donationnotrec-admin/", views.donationnotrec_admin, name="donationnotrec_admin"
    ),
    path(
        "donationdelivered-admin/",
        views.donationdelivered_admin,
        name="donationdelivered_admin",
    ),
    path("all-donations/", views.all_donations, name="all_donations"),
    path("manage-donor/", views.manage_donor, name="manage_donor"),
    path("new-volunteer/", views.new_volunteer, name="new_volunteer"),
    path("accepted-volunteer/", views.accepted_volunteer, name="accepted_volunteer"),
    path("rejected-volunteer/", views.rejected_volunteer, name="rejected_volunteer"),
    path("all-volunteer/", views.all_volunteer, name="all_volunteer"),
    path("add-area/", views.add_area.as_view(), name="add_area"),
    path("edit-area/<int:pid>", views.edit_area.as_view(), name="edit_area"),
    path("manage-area/", views.manage_area, name="manage_area"),
    path("changepwd-admin/", views.changepwd_admin.as_view(), name="changepwd_admin"),
    path("logout/", views.logoutView, name="logout"),
    # view details
    path(
        "accepted-donationdetail/<int:pid>",
        views.accepted_donationdetail,
        name="accepted_donationdetail",
    ),
    path(
        "view-volunteerdetail/<int:pid>",
        views.view_volunteerdetail,
        name="view_volunteerdetail",
    ),
    path("view-donordetail/<int:pid>", views.view_donordetail, name="view_donordetail"),
    path(
        "view-donationdetail/<int:pid>",
        views.view_donationdetail,
        name="view_donationdetail",
    ),
    # donar dashboard
    path("index-donor/", views.index_donor, name="index_donor"),
    path("donate-now/", views.donate_now.as_view(), name="donate_now"),
    path("donation-history/", views.donation_history, name="donation_history"),
    path("profile-donor/", views.profile_donor.as_view(), name="profile_donor"),
    path("changepwd-donor/", views.changepwd_donor.as_view(), name="changepwd_donor"),
    # volunteer dashboard
    path("index-volunteer/", views.index_volunteer, name="index_volunteer"),
    path("collection-req/", views.collection_req, name="collection_req"),
    path(
        "donationrec-volunteer/",
        views.donationrec_volunteer,
        name="donationrec_volunteer",
    ),
    path(
        "donationnotrec-volunteer/",
        views.donationnotrec_volunteer,
        name="donationnotrec_volunteer",
    ),
    path(
        "donationdelivered-volunteer/",
        views.donationdelivered_volunteer,
        name="donationdelivered_volunteer",
    ),
    path("profile-volunteer/", views.profile_volunteer.as_view(), name="profile_volunteer"),
    path("changepwd-volunteer/", views.changepwd_volunteer.as_view(), name="changepwd_volunteer"),
    # vew details
    path(
        "donationdetail-donor/<int:pid>",
        views.donationdetail_donor,
        name="donationdetail_donor",
    ),
    path(
        "donationrec-detail/<int:pid>",
        views.donationrec_detail,
        name="donationrec_detail",
    ),
    path(
        "donationcollection-detail/<int:pid>",
        views.donationcollection_detail,
        name="donationcollection_detail",
    ),
    path('delete_donation/<int:pid>',views.delete_donation, name='delete_donation'),
    path('delete_volunteer/<int:pid>',views.delete_volunteer, name='delete_volunteer'),
    path('delete_area/<int:pid>',views.delete_area,name='delete_area')
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import date


# Create your models here.
class Donor(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    contact = models.CharField(max_length=15,null=True)
    address = models.CharField(max_length=300,null=True)
    userpic = models.ImageField(upload_to='donor',null=True, blank=True)
    regdate = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.user.username


class Volunteer(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    contact = models.CharField(max_length=15, null=True)
    address = models.CharField(max_length=300,null=True)
    userpic = models.ImageField(upload_to='volunteer',null=True,blank=True)
    idpic = models.ImageField(upload_to='volunteer',null=True, blank=True)
    aboutme = models.CharField(max_length=300,null=True)
    status = models.CharField(max_length=20,null=True)
    regdate = models.DateTimeField(auto_now_add=True)
    adminremark = models.CharField(max_length=300,null=True)
    updationdate = models.DateField(null=True)

    def __str__(self):
        return self.user.username
    
class DonationArea(models.Model):
    areaname = models.CharField(max_length=100)
    description = models.CharField(max_length=300)
    creationdate = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.areaname
    
DONATION_CHOICES={
    ('Food Donation', 'Food Donation'),
    ('Cloth Donation', 'Cloth Donation'),
    ('Footware Donation', 'Footwear Donation'),
    ('Books Donation', 'Books Donation'),
    ('Furniture Donation', 'Furniture Donation'),
    ('Vessel Donation', 'Vessel Donation'),
    ('other', 'other'),
}

class Donation(models.Model):
    donor = models.ForeignKey(Donor, on_delete=models.CASCADE)
    donationname = models.CharField(choices=DONATION_CHOICES,max_length=100,null=True)
    donationpic = models.ImageField(upload_to='donation',null=True, blank=True)
    collectionloc = models.CharField(max_length=300,null=True)
    description = models.CharField(max_length=300,null=True)
    status = models.CharField(max_length=30,null=True)
    donationdate = models.DateField(null=True)
    adminremark = models.CharField(max_length=200,null=True)
    volunteer = models.ForeignKey(Volunteer, on_delete=models.CASCADE,null=True)
    donationarea = models.ForeignKey(DonationArea, on_delete=models.CASCADE,null=True)
    volunteerremark = models.CharField(max_length=200,null=True)
    updationdate = models.DateField(null=True)
    documentation = models.DateField(default=date.today)

    def __str__(self):
        return self.id
    

class Gallery(models.Model):
    donation = models.ForeignKey(Donation, on_delete=models.CASCADE)
    deliverypic = models.FileField(null=True)
    creationdate = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.id

app/templates/accepted-donation.html
{% extends 'base-db-admin.html' %}
{% load static %}
{% block main %}
<div class="container mt-5 vh-100 table-responsive">
    <h3>Donation Accepted</h3>
    <hr>
    <table id="mytable" class="table data">
        <thead class="table-dark">
            <tr class="text-center">
                <th scope="col">#</th>
                <th scope="col">Donation Name</th>
                <th scope="col">Donation Date</th>
                <th scope="col">Status</th>
                <th scope="col">Action</th>
              </tr>
        </thead>
        <tbody>
          {% for i in donation %}
          <tr class="text-center">
              <td>{{ forloop.counter }}</td>
              <td>{{ i.donationname }}</td>
              <td>{{ i.documentation }}</td>
              <td>{{ i.status }}</td>
              <td><a href="{% url 'view_donationdetail' i.id %}">View Details</a></td>
          </tr>
          {% endfor %}
        </tbody>
    </table>
  </div>
{% endblock main %}

app/templates/base-db-admin.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Donation & Volunteer System</title>
    <link rel="icon" type="image/x-icon" href="{% static 'images/helping-hand.png' %}" />
    <!-- Font Awesome icons (free version)-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" >

    <!-- Google fonts-->  
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@400;100;300;700&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.11.5/css/jquery.dataTables.css">

    <link rel="stylesheet" href="{% static 'css/style-admin.css' %}">
</head>

<body class="bg-light bg-gradient">
    <div class="sidebar">
        <div class="logo_content">
            <div class="logo">
                <i id="icon-home" class="fa fa-home" aria-hidden="true"></i>
                <div class="logo_name">Admin</div>
            </div>
            <span id="btn-sidebar"><i class="fa fa-bars"  aria-hidden="true"></i></span>
        </div>
        <div class="profile_content">
            <div class="profile">
                <div class="profile_details">
                    <img src="{% static 'images/logo1.png' %}"  alt="" >
                    <div class="name_job">
                        <div class="name">{{request.user.first_name}} {{request.user.last_name}}</div>
                        <div class="email">{{request.user.email}}</div>
                    </div>
                </div>
            </div>
        </div>
        <ul class="nav_list">
            <!-- <li>
                
                <i id="icon-search" class="fa fa-search" aria-hidden="true"></i>
                <input type="text" placeholder="Search...">
            </li> -->
            <li>
                <a href="{% url 'index_admin' %}">
                    <!--grid -->
                    <i id="icon" class="fa fa-th-large" aria-hidden="true"></i>
                    <span class="links_name">Dashboard</span>
                </a>
            </li>
            <li >
                <!-- <a href="#">
                    
                    <i id="icon" class="fa fa-users" aria-hidden="true"></i>
                    <span class="links_name">Donor</span> 
                    
                </a> -->
                
               <a href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    <i id="icon" class="fa fa-users" aria-hidden="true"></i>
                    <span class="links_name">Donation</span> 
                    <i class="down-arrow fa-solid fa-angle-down"></i>
                  </a>
                  <ul class="dropdown-menu dropdown-menu-dark " aria-labelledby="navbarDropdown">
                    <li><a class="dropdown-item" href="{% url 'pending_donation' %}">New Donation Request</a></li>
                    <li><a class="dropdown-item" href="{% url 'accepted_donation' %}">Accepted Donation</a></li>
                    <li><a class="dropdown-item" href="{% url 'rejected_donation' %}">Rejected Donation</a></li>
                    <li><a class="dropdown-item" href="{% url 'volunteerallocated_donation' %}">Volunteer Allocated Donation</a></li>
                    <li><a class="dropdown-item" href="{% url 'donationrec_admin' %}">Donation Received</a></li>
                    <li><a class="dropdown-item" href="{% url 'donationnotrec_admin' %}">Donation Not Received</a></li>
                    <li><a class="dropdown-item" href="{% url 'donationdelivered_admin' %}">Donation Delivered</a></li>
                    <li><a class="dropdown-item" href="{% url 'all_donations' %}">All Donation</a></li>
                  </ul>  
            </li>
            <li>
                <a href="{% url 'manage_donor' %}">
                    <!--grid -->
                    <i id="icon" class="fa fa-info-circle" aria-hidden="true"></i>
                    <span class="links_name">Manage Donor</span>
                </a>
            </li>
            <li>
                
                <a href="#" id="navbarDropdownvol" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    <i id="icon" class="fa fa-user-circle" aria-hidden="true"></i>
                    <span class="links_name">Volunteer</span>
                    <i class="down-arrow fa-solid fa-angle-down"></i>
                  </a>
                  <ul class="dropdown-menu dropdown-menu-dark " aria-labelledby="navbarDropdownvol">
                    <li><a class="dropdown-item" href="{% url 'new_volunteer' %}">New Volunteer Request</a></li>
                    <li><a class="dropdown-item" href="{% url 'accepted_volunteer' %}">Accepted Volunteer</a></li>
                    <li><a class="dropdown-item" href="{% url 'rejected_volunteer' %}">Rejected Volunteer</a></li>
                    <li><a class="dropdown-item" href="{% url 'all_volunteer' %}">All Volunteer</a></li>
                   </ul>  
            </li>
            <li>
                
                <a href="#" id="navbarDropdownarea" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    <i id="icon" id="icon" class="fa fa-address-card" aria-hidden="true"></i>
                    <span class="links_name">Area</span>
                    <i class="down-arrow fa-solid fa-angle-down"></i>
                  </a>
                  <ul class="dropdown-menu dropdown-menu-dark " aria-labelledby="navbarDropdownarea">
                    <li><a class="dropdown-item" href="{% url 'add_area' %}">Add donation Area</a></li>
                    <li><a class="dropdown-item" href="{% url 'manage_area' %}">Manage Donation Area</a></li>
                   </ul>  
            </li>
            {% comment %} <li>
                <a href="#">
                    <!--info -->
                    <i id="icon" class="fa fa-info-circle" aria-hidden="true"></i>
                    <span class="links_name">Profile</span>
                </a>
            </li> {% endcomment %}
            <li>
                <a href="{% url 'changepwd_admin' %}">
                    <!--key -->
                    <i id="icon" class="fa fa-key" aria-hidden="true"></i>
                    <span class="links_name">Change Password</span>
                </a>
            </li>
            <li>
                <a href="{% url 'logout' %}">
                    <!--logout -->
                    <i id="icon" class="fa fa-sign-out" aria-hidden="true"></i>
                    <span class="links_name">Logout</span>
                </a>
            </li>
            
        </ul>
    </div>
    <div class="home_content">
        {% block main %}
        {% endblock main %}
    </div>
    {% include 'base-db-footer.html' %}

app/templates/base-db-donor.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Donation & Volunteer System</title>
    <link rel="icon" type="image/x-icon" href="{% static 'images/helping-hand.png' %}" />
    <!-- Font Awesome icons (free version)-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" >

    <!-- Google fonts-->  
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@400;100;300;700&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.11.5/css/jquery.dataTables.css">

    <link rel="stylesheet" href="{% static 'css/style-admin.css' %}">
    <style>
        .sidebar{
            background: #581845;
        }        
        body{
            background-image: linear-gradient(45deg, #ECD1E4, #ECA4D7, #ECD1E4);
        }
    </style>
</head>

<body >
    <div class="sidebar">
        <div class="logo_content">
            <div class="logo">
                <i id="icon-home" class="fa fa-home" aria-hidden="true"></i>
                <div class="logo_name">Donor</div>
            </div>
            <span id="btn-sidebar"><i class="fa fa-bars"  aria-hidden="true"></i></span>
        </div>
        <div class="profile_content">
            <div class="profile">
                <div class="profile_details">
                    <img src="{{request.user.donor_set.all.0.userpic.url}}"  alt="" >
                    <div class="name_job">
                        <div class="name">{{request.user.first_name}} {{request.user.last_name}}</div>
                        <div class="email">{{request.user.email}}</div>
                    </div>
                </div>
            </div>
        </div>
        <ul class="nav_list">
            <!-- <li>
                
                <i id="icon-search" class="fa fa-search" aria-hidden="true"></i>
                <input type="text" placeholder="Search...">
            </li> -->
            <li>
                <a href="{% url 'index_donor' %}">
                    <!--grid -->
                    <i id="icon" class="fa fa-th-large" aria-hidden="true"></i>
                    <span class="links_name">Dashboard</span>
                </a>
            </li>
            <li >
                <a href="{% url 'donate_now' %}">
                    
                    <i id="icon" class="fa fa-users" aria-hidden="true"></i>
                    <span class="links_name">Donate Now</span> 
                    
                </a> 
            </li>
            <li>
                <a href="{% url 'donation_history' %}">
                    <!--grid -->
                    <i id="icon" class="fa fa-info-circle" aria-hidden="true"></i>
                    <span class="links_name">Donation History</span>
                </a>
            </li>
            
            <li>
                <a href="{% url 'profile_donor' %}">
                    <!--user -->
                    <i id="icon" class="fa fa-user" aria-hidden="true"></i>
                    <span class="links_name">Profile</span>
                </a> 
            </li>
            
            <li>
                <a href="{% url 'changepwd_donor' %}">
                    <!--key -->
                    <i id="icon" class="fa fa-key" aria-hidden="true"></i>
                    <span class="links_name">Change Password</span>
                </a> 
            </li>
            <li>
                <a href="{% url 'logout' %}">
                    <!--logout -->
                    <i id="icon" class="fa fa-sign-out" aria-hidden="true"></i>
                    <span class="links_name">Logout</span>
                </a>
            </li>
            
        </ul>
    </div>
    <div class="home_content">
        {% block main %}
        {% endblock main %}
    </div>   
    {% include 'base-db-footer.html' %}         

app/templates/changepwd-volunteer.html
{% extends 'base-db-volunteer.html' %}
{% load static %}
{% block main %}
<div class="container mt-5 vh-100 table-responsive">
    <h3>Change Password</h3>
    <hr>
    <div class="row">

            <form action="" method="post" novalidate>
                {% csrf_token %}
                {% for fm in form %}
                    <div class="form-group col-sm-12 p-3">
                        {{fm}} <small class="text-danger">{{fm.errors|striptags}}</small>
                    </div>
                {% endfor %}
                <div class="d-grid gap-2">
                    <input type="submit" value="Submit" class="mt-4 px-3 btn btn-primary">
                </div>
            
            </form>
        
    
    </div>
{% if form.non_field_errors %}
        {% for error in form.non_field_errors %}
            <p class="alert alert-danger my-3">{{error}}</p>
        {% endfor %}
{% endif %}
    
{% if messages %}
    {% for message in messages %}
            <h3 {% if message.tags %} class="text-center alert alert-{{message.tags}} my-5" {% endif %}>
            {{message}}
            </h3>
    {% endfor %}
{% endif %}
    </div>
{% endblock main %}

app/templates/collection-req.html
{% extends 'base-db-volunteer.html' %}
{% load static %}
{% block main %}
<div class="container mt-5 vh-100 table-responsive">
    <h3>New Donation Collection Request</h3>
    <hr>
    <table id="mytable" class="table data">
        <thead class="table-dark">
            <tr class="text-center">
                <th scope="col">#</th>
                <th>Donation Name</th>
                <th>Donation Date</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            {% for i in donation %}
            <tr class="text-center">
                <th>{{ forloop.counter }}</th>
                <td>{{ i.donationname }}</td>
                <td>{{ i.donationdate }}</td>
                <td><a href="{% url 'donationcollection_detail' i.id %}">View Details</a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock main %}

app/templates/donationnotrec-volunteer.html
{% extends 'base-db-volunteer.html' %}
{% load static %}
{% block main %}
<div class="container mt-5 vh-100 table-responsive">
    <h3>Donation Not Received</h3>
    <hr>
    <table id="mytable" class="table data">
        <thead class="table-dark">
            <tr class="text-center">
                <th scope="col">#</th>
                <th>Donation Name</th>
                <th>Donation Date</th>
                <th>Status</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            {% for i in donation %}
            <tr class="text-center">
                <th>{{ forloop.counter }}</th>
                <td>{{ i.donationname }}</td>
                <td>{{ i.donationdate }}</td>
                <td>{{ i.status }}</td>
                <td><a href="{% url 'donationcollection_detail' i.id %}">View Details</a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock main %}

app/templates/donationrec-admin.html
{% extends 'base-db-admin.html' %}
{% load static %}
{% block main %}
<div class="container mt-5 vh-100 table-responsive">
    <h3>Donation Received But Not Delivered Yet</h3>
    <hr>
    <table id="mytable" class="table data">
        <thead class="table-dark">
            <tr class="text-center">
                <th scope="col">#</th>
                <th scope="col">Donation Name</th>
                <th scope="col">Donation Date</th>
                <th scope="col">Status</th>
                <th scope="col">Action</th>
              </tr>
        </thead>
        <tbody>
          {% for i in donation %}
          <tr class="text-center">
              <td>{{ forloop.counter }}</td>
              <td>{{ i.donationname }}</td>
              <td>{{ i.documentation }}</td>
              <td>{{ i.status }}</td>
              <td><a href="{% url 'view_donationdetail' i.id %}">View Details</a></td>
          </tr>
          {% endfor %}
        </tbody>
    </table>
  </div>
{% endblock main %}

app/templates/edit-area.html
{% extends 'base-db-admin.html' %}
{% load static %}
{% block main %}
<div class="container mt-5 vh-100 table-responsive">
    <h3>Edit Donation Area Detail</h3>
    <hr>
    <div class="row">
      <div class="col-sm-12 p-2">
          <div class="form-group">
              <label>Donation Area Name</label>
              <input type="text" name="areaname"  class="form-control" placeholder="Donation Area">
          </div>
      </div>

      <div class="col-sm-12 p-2">
          <div class="form-group">
              <label>Description</label>
              <textarea name="description"  class="form-control" placeholder="Description"></textarea>
          </div>
      </div>
  
    <input type="submit" value="Submit" class="m-2 px-3 btn btn-primary">
    </div>
  </div>
{% endblock main %}

app/templates/password_reset_complete.html
{% extends 'base.html' %}
{% load static %}
{% block main %}
<section class="vh-100 gradient-custom">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-12 col-md-8 col-lg-6 col-xl-5">
        <div class="card bg-dark text-white" style="border-radius: 1rem;">
          <div class="card-body p-5 text-center">

            <div class="mb-md-5 mt-md-4 pb-5">

              <h2 class="fw-bold mb-2 text-uppercase"> Password Reset Completed</h2>
              
              <div><iframe src="https:/giphy.com/embed/ibolLe3mOqHE3PQTtk" width="200" height="200" frameborder="0" class="giphy-embed" allowFullScreen></iframe></div>

          </div>
        </div>
        {% if form.non_field_errors %}
        {% for error in form.non_field_errors %}
          <p class="alert alert-danger my-3">{{error}}</p>
        {% endfor %}
      {% endif %}

      
      </div>
    </div>
  </div>
</section>
{% endblock main %}

app/templates/pending-donation.html
{% extends 'base-db-admin.html' %}
{% load static %}

{% block main %}
<div class="container mt-5 vh-100 table-responsive">
    <h3>New Donation Request List</h3>
    <hr>
    <table id="mytable" class="table data">
        <thead class="table-dark">
            <tr class="text-center">
                <th scope="col">#</th>
                <th scope="col">Donation Name</th>
                <th scope="col">Donation Date</th>
                <th scope="col">Status</th>
                <th scope="col">Action</th>
            </tr>
        </thead>
        <tbody>
            {% for i in donation %}
                <tr class="text-center">
                    <td>{{ forloop.counter }}</td>
                    <td>{{ i.donationname }}</td>
                    <td>{{ i.documentation }}</td>
                    <td>{{ i.status }}</td>
                    <td><a href="{% url 'view_donationdetail' i.id %}">View Details</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock main %}

app/templates/view-donordetail.html
{% extends 'base-db-admin.html' %}
{% load static %}
{% block main %}
<div class="container mt-5 vh-100 table-responsive">
  <h3>View Donor Detail</h3>
  <hr>
  <table id="mytable" class="table data ">
      <tbody>
          <tr class="align-middle text-center" >
              <th colspan="4"><h3>Donor Details</h3></th>
          </tr>
          <tr class="align-middle text-center">
            <td><h5>Donor Name</h5></td>
            <td><h5 class="text-secondary">Nilesh Borate</h5></td>
            <td><h5>Donor Contact</h5></td>
            <td><h5 class="text-secondary">9000000000</h5></td>
        </tr>
          <tr class="align-middle text-center">
              <td><h5>Email</h5></td>
              <td><h5 class="text-secondary">nilesh@gmail.com</h5></td>
              <td><h5>Donor Pic</h5></td>
            <td><img src="{% static 'images/cloth-donation.jfif' %}" width="80" height="80" /></td>
          </tr>
        
        <tr align="center">
          <td colspan="4" style="font-size:20px;color:red">
              <a href="#" onclick="return confirm('Are You Sure?')" class="text-primary">Delete</a>
          </td>
        </tr>

      </tbody>
  </table>
</div>
{% endblock main %}

app/templates/volunteerallocated-donation.html
{% extends 'base-db-admin.html' %}
{% load static %}
{% block main %}
<div class="container mt-5 vh-100 table-responsive">
    <h3>All Allocated Donation List</h3>
    <hr>
    <table id="mytable" class="table data">
        <thead class="table-dark">
            <tr class="text-center">
                <th scope="col">#</th>
                <th scope="col">Donation Name</th>
                <th scope="col">Donation Date</th>
                <th scope="col">Status</th>
                <th scope="col">Action</th>
              </tr>
        </thead>
        <tbody>
            {% for i in donation %}
            <tr class="text-center">
                <td>{{ forloop.counter }}</td>
                <td>{{ i.donationname }}</td>
                <td>{{ i.documentation }}</td>
                <td>{{ i.status }}</td>
                <td><a href="{% url 'view_donationdetail' i.id %}">View Details</a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
  </div>
{% endblock main %}